<?php

namespace AppBundle\Repository;

/**
 * ImagenMaquinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenMaquinaRepository extends \Doctrine\ORM\EntityRepository
{
}
