<?php

namespace AppBundle\Repository;

/**
 * LikesProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikesProyectoRepository extends \Doctrine\ORM\EntityRepository
{
}
