<?php

namespace AppBundle\Repository;

/**
 * link_calendarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class link_calendarioRepository extends \Doctrine\ORM\EntityRepository
{
}
