<?php

namespace AppBundle\Repository;

/**
 * link_calendario_usuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class link_calendario_usuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
