<?php

namespace AppBundle\Repository;

/**
 * LinksProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinksProyectoRepository extends \Doctrine\ORM\EntityRepository
{
}
